name: Enviar Tweet GM Diário

on:
  schedule:
    - cron: '0 12 * * *'  # todos os dias às 12:00 UTC
  workflow_dispatch:       # permite rodar manualmente

jobs:
  send_gm_tweet:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install tweepy python-dotenv

      - name: Enviar Tweet GM
        env:
          TWITTER_API_KEY: ${{ secrets.TWITTER_API_KEY }}
          TWITTER_API_SECRET: ${{ secrets.TWITTER_API_SECRET }}
          TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          TWITTER_ACCESS_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
        run: python send_gm_tweet.py
